name: 金融市场分析自动化

on:
  schedule:
    # 每天早上8点运行（北京时间）
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run_market_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 如果您的脚本有依赖项，请在这里安装
          # pip install -r requirements.txt
      
      - name: Run market analysis
        run: python automatic_market_update.py once
      
      - name: Check if today is trading day
        id: trading_day
        run: |
          # 检查是否为周一至周五
          if [ $(date +%u) -lt 6 ]; then
            echo "trading_day=true" >> $GITHUB_ENV
          else
            echo "trading_day=false" >> $GITHUB_ENV
          fi
      
      - name: Run trading analysis (only on trading days)
        if: env.trading_day == 'true'
        run: python automatic_trading_analysis.py test
      
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m '自动更新金融市场分析报告'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}